<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-search</name>
   <tag></tag>
   <elementGuidId>8bc9bd40-ecb6-43a1-bac8-27f03a606b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-search-bar[@id='searchQuery']/mat-form-field</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-form-field.mat-form-field.mat-search_field.ng-tns-c21-6.mat-primary.ng-tns-c123-1.ng-trigger.ng-trigger-slideInOut.mat-form-field-type-mat-input.mat-form-field-appearance-standard.mat-form-field-can-float.ng-untouched.ng-pristine.ng-valid.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Click to search&quot;i >> mat-form-field</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-form-field</value>
      <webElementGuid>ae7221ce-95cb-4dc6-881f-99442776a743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field mat-search_field ng-tns-c21-6 mat-primary ng-tns-c123-1 ng-trigger ng-trigger-slideInOut mat-form-field-type-mat-input mat-form-field-appearance-standard mat-form-field-can-float ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ec8a2ba3-5c5d-452d-a7ca-4d80cc75973c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchQuery&quot;)/mat-form-field[@class=&quot;mat-form-field mat-search_field ng-tns-c21-6 mat-primary ng-tns-c123-1 ng-trigger ng-trigger-slideInOut mat-form-field-type-mat-input mat-form-field-appearance-standard mat-form-field-can-float ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>c9ed0106-7163-4823-a353-e51422882b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-search-bar[@id='searchQuery']/mat-form-field</value>
      <webElementGuid>ce2bc038-1ffe-4bea-b593-4f17b8250809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OWASP Juice Shop'])[4]/following::mat-form-field[1]</value>
      <webElementGuid>cc81a88b-5c41-4fea-83cd-6c773bcda3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v17.1.1'])[1]/following::mat-form-field[1]</value>
      <webElementGuid>af38cd9e-a32a-4172-8e7f-5000027f8d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_circle'])[1]/preceding::mat-form-field[1]</value>
      <webElementGuid>d17872c9-c451-4a39-966e-39026f29a872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/preceding::mat-form-field[1]</value>
      <webElementGuid>5574e29f-0cc2-4e8b-a957-4896b8ad14bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field</value>
      <webElementGuid>9ef07bb0-da1f-4535-8c88-080975d3b370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
