<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat Password</name>
   <tag></tag>
   <elementGuidId>5f379e86-34ba-4e74-85d3-2b5029616009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatPasswordControl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#repeatPasswordControl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Field to confirm the password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>129f03b3-638c-49b2-aad6-1a7df2158cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatPasswordControl</value>
      <webElementGuid>e88ca640-5898-494b-9e67-e7bcf223f3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5283f7a2-89c2-4534-8cdf-3164b72ecd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field to confirm the password</value>
      <webElementGuid>67b1009b-b5a8-41ad-9c33-ea219afacfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-15 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>84260778-ffa7-45fe-805d-699e440e1ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-hint-2</value>
      <webElementGuid>e2b1b4ea-0925-46d6-a88e-32754f8e5458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e21898d-77fc-4315-8f81-eeaa39fd5515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatPasswordControl&quot;)</value>
      <webElementGuid>2a92904d-e8d1-4b85-b3ad-bf42b3c87bd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatPasswordControl']</value>
      <webElementGuid>3ea5743e-59fb-44c2-98f6-cb5a4ce0e8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>14675246-3972-4a72-b1c0-49271ae88d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>7cf60b07-f684-4774-b223-569b4d61dd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'repeatPasswordControl' and @type = 'password']</value>
      <webElementGuid>d5078899-fd60-4f1c-9f8f-924dcc4d6c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
